#!/usr/bin/env python3
"""Capture still RGB+depth frames from the D455 for offline perception work.

Saves, per shot:
  <tag>_NNN_color.png   8-bit BGR, the color frame
  <tag>_NNN_depth.png   16-bit single channel, depth in millimetres, aligned to color
  <tag>_NNN_meta.json   intrinsics + depth scale, everything needed to deproject

The depth PNG is aligned to the color frame, so pixel (u,v) means the same thing
in both. That is what lets a detection box in the color image be turned into a
3D point later.

Note: only one process can hold the RealSense at a time. Stop d455_viewer first.

Usage:
  ./capture_stills.py --tag tape -n 10 --interval 2.0
  ./capture_stills.py --tag tape -n 1               # single shot
"""

import argparse
import json
import os
import sys
import time

import cv2
import numpy as np
import pyrealsense2 as rs

COLOR_W, COLOR_H = 1280, 720
DEPTH_W, DEPTH_H = 848, 480
FPS = 30

# Frames to discard so auto-exposure and white balance settle before the first
# save. Without this the early shots come out dark and are useless for tuning.
WARMUP_FRAMES = 40


def write_ply(path, color_bgr, depth_mm, meta, stride=1):
    """Write a colored point cloud as a binary little-endian PLY.

    Depth is already aligned to color, so pixel (u,v) indexes both images and
    every 3D point carries the RGB of the same pixel. Points with zero depth are
    dropped - the D455 reports 0 where stereo found no match, and keeping those
    would put a wall of fake points at the origin.
    """
    h, w = depth_mm.shape[:2]
    us, vs = np.meshgrid(np.arange(0, w, stride, dtype=np.float32),
                         np.arange(0, h, stride, dtype=np.float32))
    z = depth_mm[::stride, ::stride].astype(np.float32) / 1000.0  # mm -> m
    valid = z > 0
    if not valid.any():
        return 0

    x = (us - meta["ppx"]) / meta["fx"] * z
    y = (vs - meta["ppy"]) / meta["fy"] * z
    rgb = cv2.cvtColor(color_bgr[::stride, ::stride], cv2.COLOR_BGR2RGB)

    pts = np.empty(int(valid.sum()), dtype=[
        ("x", "<f4"), ("y", "<f4"), ("z", "<f4"),
        ("red", "u1"), ("green", "u1"), ("blue", "u1")])
    pts["x"] = x[valid]
    pts["y"] = y[valid]
    pts["z"] = z[valid]
    pts["red"] = rgb[..., 0][valid]
    pts["green"] = rgb[..., 1][valid]
    pts["blue"] = rgb[..., 2][valid]

    header = (
        "ply\n"
        "format binary_little_endian 1.0\n"
        "comment generated by capture_stills.py, camera optical frame, metres\n"
        "element vertex %d\n"
        "property float x\nproperty float y\nproperty float z\n"
        "property uchar red\nproperty uchar green\nproperty uchar blue\n"
        "end_header\n" % pts.size)
    with open(path, "wb") as f:
        f.write(header.encode("ascii"))
        pts.tofile(f)
    return pts.size


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=os.path.join(os.path.dirname(os.path.abspath(__file__)), "stills"),
                    help="output directory (default: ./stills)")
    ap.add_argument("--tag", default="scene", help="filename prefix")
    ap.add_argument("-n", "--num", type=int, default=10, help="number of shots")
    ap.add_argument("--interval", type=float, default=2.0,
                    help="seconds between shots, so you can move things around")
    ap.add_argument("--ply", action="store_true",
                    help="also write a colored point cloud (<tag>_NNN.ply)")
    ap.add_argument("--ply-stride", type=int, default=1,
                    help="subsample the cloud by this factor (default 1 = full)")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)

    pipe = rs.pipeline()
    cfg = rs.config()
    cfg.enable_stream(rs.stream.color, COLOR_W, COLOR_H, rs.format.bgr8, FPS)
    cfg.enable_stream(rs.stream.depth, DEPTH_W, DEPTH_H, rs.format.z16, FPS)

    try:
        profile = pipe.start(cfg)
    except RuntimeError as e:
        print("Failed to start the camera: %s" % e, file=sys.stderr)
        print("Is d455_viewer still running? Only one process can hold the D455.",
              file=sys.stderr)
        return 1

    align = rs.align(rs.stream.color)
    depth_scale = profile.get_device().first_depth_sensor().get_depth_scale()

    dev = profile.get_device()
    print("Device: %s  serial %s" % (dev.get_info(rs.camera_info.name),
                                     dev.get_info(rs.camera_info.serial_number)))
    print("Warming up (%d frames) for auto-exposure..." % WARMUP_FRAMES)
    for _ in range(WARMUP_FRAMES):
        pipe.wait_for_frames()

    saved = 0
    try:
        for i in range(args.num):
            if i > 0:
                time.sleep(args.interval)

            frames = align.process(pipe.wait_for_frames())
            color_frame = frames.get_color_frame()
            depth_frame = frames.get_depth_frame()
            if not color_frame or not depth_frame:
                print("  shot %d: dropped frame, skipping" % i)
                continue

            color = np.asanyarray(color_frame.get_data())
            depth = np.asanyarray(depth_frame.get_data())  # uint16, depth units

            # Convert depth units to millimetres so the PNG is self-describing.
            depth_mm = (depth.astype(np.float32) * depth_scale * 1000.0)
            depth_mm = np.clip(depth_mm, 0, 65535).astype(np.uint16)

            intr = color_frame.profile.as_video_stream_profile().intrinsics
            meta = {
                "width": intr.width,
                "height": intr.height,
                "fx": intr.fx, "fy": intr.fy,
                "ppx": intr.ppx, "ppy": intr.ppy,
                "model": str(intr.model),
                "coeffs": list(intr.coeffs),
                "depth_scale_m_per_unit": depth_scale,
                "depth_units_in_png": "millimetres",
                "depth_aligned_to": "color",
            }

            base = os.path.join(args.out, "%s_%03d" % (args.tag, i))
            cv2.imwrite(base + "_color.png", color)
            cv2.imwrite(base + "_depth.png", depth_mm)
            with open(base + "_meta.json", "w") as f:
                json.dump(meta, f, indent=2)

            valid = float((depth_mm > 0).mean()) * 100.0
            print("  saved %s_color.png   (depth valid %.1f%% of pixels)"
                  % (os.path.basename(base), valid))

            if args.ply:
                n = write_ply(base + ".ply", color, depth_mm, meta, args.ply_stride)
                size_mb = os.path.getsize(base + ".ply") / 1e6
                print("        %s.ply  %d points, %.1f MB"
                      % (os.path.basename(base), n, size_mb))
            saved += 1
    finally:
        pipe.stop()

    print("\n%d shot(s) written to %s" % (saved, args.out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
